/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PercentsRouteImport } from './routes/percents'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as ArticleRouteImport } from './routes/article'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PercentsRoute = PercentsRouteImport.update({
  id: '/percents',
  path: '/percents',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleRoute = ArticleRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/article': typeof ArticleRoute
  '/converter': typeof ConverterRoute
  '/news': typeof NewsRoute
  '/percents': typeof PercentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/article': typeof ArticleRoute
  '/converter': typeof ConverterRoute
  '/news': typeof NewsRoute
  '/percents': typeof PercentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/article': typeof ArticleRoute
  '/converter': typeof ConverterRoute
  '/news': typeof NewsRoute
  '/percents': typeof PercentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/article' | '/converter' | '/news' | '/percents'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/article' | '/converter' | '/news' | '/percents'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/article'
    | '/converter'
    | '/news'
    | '/percents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticleRoute: typeof ArticleRoute
  ConverterRoute: typeof ConverterRoute
  NewsRoute: typeof NewsRoute
  PercentsRoute: typeof PercentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/percents': {
      id: '/percents'
      path: '/percents'
      fullPath: '/percents'
      preLoaderRoute: typeof PercentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article': {
      id: '/article'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof ArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticleRoute: ArticleRoute,
  ConverterRoute: ConverterRoute,
  NewsRoute: NewsRoute,
  PercentsRoute: PercentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
